### ISSUE TITLE
Add notification management

### ISSUE THREAD

**Issue by realvarx** [atsign-foundation/at_python#8]
### Is your feature request related to a problem? Please describe.

One crucial aspect in the development of the SDK is the integration of the notification functionality, encompassing the ability to send, receive, and monitor notifications. Prior to progressing with the porting of tools that rely on this feature, such as [sshnp](https://github.com/atsign-foundation/sshnoports), it is highly recommended to prioritize the development of this functionality.

### Describe the solution you'd like

Create `Notification` and `NotificationService` classes.

### Original Dart/Java SDKs code references:
- [AtNotification - Dart](https://github.com/atsign-foundation/at_client_sdk/blob/trunk/packages/at_client/lib/src/response/at_notification.dart)
- [NotificationServiceImpl - Dart](https://github.com/atsign-foundation/at_client_sdk/blob/trunk/packages/at_client/lib/src/service/notification_service_impl.dart)
- [Metadata - Dart](https://github.com/atsign-foundation/at_tools/blob/trunk/packages/at_commons/lib/src/keystore/at_key.dart)
- [Constants - Dart](https://github.com/atsign-foundation/at_tools/blob/trunk/packages/at_commons/lib/src/at_constants.dart)
- [Metadata - Java](https://github.com/JeremyTubongbanua/at_java/blob/notification/at_client/src/main/java/org/atsign/common/Keys.java)
- [AtNotification - Java](https://github.com/JeremyTubongbanua/at_java/blob/notification/at_client/src/main/java/org/atsign/client/api/notification/AtNotification.java)
- https://github.com/atsign-foundation/at_java/pull/63
- [AtMonitorConnection - Java](https://github.com/atsign-foundation/at_java/blob/trunk/at_client/src/main/java/org/atsign/client/api/impl/connections/AtMonitorConnection.java)

### Task list (not necessarily complete or in the correct order):
(Steps inspired by @JeremyTubongbanua 's https://github.com/atsign-foundation/at_java/pull/63 changelog)
- [x] Create AtNotification class
- [x] Expand Metadata class (new parameters)
- [x] Create NotifyVerbBuilder
- [ ] Create `NotificationService` class, and `get_notification_service` method for `AtClient`
- [ ] `NotificationEnums`

**Comment by realvarx** [comment]
Just to keep the issue updated, notification management system was implemented in https://github.com/atsign-foundation/at_python/pull/21 and @Xlin123 added diverse features such as notify verb, more metadata parameters, iv and tests in https://github.com/atsign-foundation/at_python/pull/31.
